# Generated by Django 6.0.5 on 2026-05-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='instructor',
        ),
    ]
